### ISSUE TITLE
Actual 2D floor plan images as Density Map

### ISSUE THREAD

**Issue by ogencoglu** [ywyue/RoomFormer#10]
Thanks for the great work!

This is not an issue but more of a question. Can your work and implementation be utilized to detect the rooms and walls directly from a 2D floor plan image? Meaning that, if I bypass the 3D part, can actual 2D floorplan images or pdfs be somehow used as a "Density Map" in your setting?

**Comment by ywyue** [comment]
Thanks for your interest!

Yes, the 3D part is not the direct input to our model, so it can be bypassed as long as you have the 2D input. Please feel free to show an example image of such actual 2D floor plans! It should work if you have enough training samples: actual 2D floor plan images + annotations of rooms and walls (and windows, etc.)

**Comment by ywyue** [comment]
Close this issue for now. Feel free to reopen it if you have further concerns!

**Comment by ogencoglu** [comment]
Here are couple of examples of floorplan images.

![Ia_AP2022_sommaire_0](https://github.com/ywyue/RoomFormer/assets/8182738/ffac4a7c-052e-4930-a3c5-45e61cde6a2e)

![train_0004](https://github.com/ywyue/RoomFormer/assets/8182738/f811e28e-022e-4876-bd3f-2f9c9902bec6)

![0002](https://github.com/ywyue/RoomFormer/assets/8182738/dc3d078f-7b4f-4dde-bd74-0d6f92df7304)

![211](https://github.com/ywyue/RoomFormer/assets/8182738/0c9d1633-0bff-4d23-8637-152d9e21f5b5)

So it can be quite arbitrary style. I can of course do some pre-processing (greyscale, clean the text etc.) to make it look similar to your density maps. 

What would be the easiest way to try just inference (no training) using these images as density maps? Which part of the codebase would be relevant?

Also would it be possible to upload one example of density map to understand the format and structure?

Thank you!

**Comment by ywyue** [comment]
First, let me show you one example of a density map: 
![00000](https://github.com/ywyue/RoomFormer/assets/40747438/ab6667af-de3d-464a-9508-f219878804d1)

The density map has 256×256 pixels, and the density value at each pixel is the number of projected points to that pixel divided by the maximum point number so that it is normalized to [0, 1] (finally re-scaled to [0,255]). So walls would have high-density values since they have many points in the vertical direction.

> What would be the easiest way to try just inference (no training) using these images as density maps? Which part of the codebase would be relevant?

One hacky way is to replace one density map in the test set as your density map, e.g., 03250.png, and then run the evaluation script. Just make sure your density map is also 256 × 256. In this way, you should obtain the qualitative results quickly. 

However, I don't expect the model would perform well if no training due to the large domain gap.

**Comment by claumeh** [comment]
Thanks for your guidance. I have tried your recommended approach with the following density image. But the results where close to zero. Here is the density image I used and replaced the original one in /train dir: I have created the png with your code based on my own point cloud. What does the point need to have in terms of requirements, e.g. density?
![03255](https://github.com/user-attachments/assets/8bac994a-1478-4f4c-926b-4fbdc31b0735)

Can you help me out here or check the density image for solid strucure?

**Comment by guker** [comment]
> Thanks for your guidance. I have tried your recommended approach with the following density image. But the results where close to zero. Here is the density image I used and replaced the original one in /train dir: I have created the png with your code based on my own point cloud. What does the point need to have in terms of requirements, e.g. density? ![03255](https://private-user-images.githubusercontent.com/175531808/348654113-8bac994a-1478-4f4c-926b-4fbdc31b0735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjY4MDUsIm5iZiI6MTcyMTcyNjUwNSwicGF0aCI6Ii8xNzU1MzE4MDgvMzQ4NjU0MTEzLThiYWM5OTRhLTE0NzgtNGY0Yy05MjZiLTRmYmRjMzFiMDczNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwOTIxNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWE2NmY0NGNiZWFhOTVkODNmOTExY2I0YTIwMGU3NmRmYzM1MDI0MDVhZmE4NGUwOTg1MWQ3MjMzOTlkNzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ws5hqakQC5TO4GS63a0B3m0knRdF5Z8q8CHsa0mb2fA)
> 
> Can you help me out here or check the density image for solid strucure?

I have same question！ but I rotate density map image so that it align axis， it works

**Comment by claumeh** [comment]
Thanks for the update @guker

Did you manually rotate or have code by chance? How does the result look like?
