### ISSUE TITLE
Can you share the demo code? Enter DensityMap to obtain the results, as well as the result visualization code?

### ISSUE THREAD

**Issue by zhangzscn** [ywyue/RoomFormer#11]

**Comment by ywyue** [comment]
Hi, thanks for your interest! We already included the inference and visualization code. 

Please follow ```./tools/eval_stru3d.sh``` to perform the inference given the density maps of Structured3D.

By default, the inference will also generate some qualitative results (see [here](https://github.com/ywyue/RoomFormer/blob/36c7d00a5200b4ef3743086fc71df822ec2ac7b8/eval.py#L85))

**Comment by zhangzscn** [comment]
thanks
