### ISSUE TITLE
generate_point_cloud_stru3d.py error

### ISSUE THREAD

**Issue by zhangzscn** [ywyue/RoomFormer#12]
An error occurred while trying to convert the stru3d dataset to a point cloud. It seems that the dataset I downloaded did not have the same directory as in the code after extracting it.

error：

Creating point cloud from perspective views...
  0%|                                                                                                                                   | 0/3500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data_preprocess/stru3d/generate_point_cloud_stru3d.py", line 29, in <module>
    main(config())
  File "data_preprocess/stru3d/generate_point_cloud_stru3d.py", line 19, in main
    scenes = os.listdir(os.path.join(data_root, part, 'Structured3D'))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data2/数据集/Structured3D/Structured3D/scene_02893/Structured3D'

stru3d data set unzipped directory：
![2023-06-27 11-29-02屏幕截图](https://github.com/ywyue/RoomFormer/assets/13817275/1e434205-884c-458c-8161-b8d98850e106)

**Comment by ywyue** [comment]
Hi, it seems that the ```--data_root``` ([here](https://github.com/ywyue/RoomFormer/blob/36c7d00a5200b4ef3743086fc71df822ec2ac7b8/data_preprocess/stru3d/generate_point_cloud_stru3d.py#L9C8-L9C9)) was not correct. 

E.g., for the following data structure, the ```--data_root``` should be set as ```Structured3D_panorama```
```
Structured3D_panorama/
└── Structured3D_panorama_00/
    └── Structured3D/
        └── scene_00000/
            ├── annotation_3d.json
            └── 2D_rendering
               ├── 485142
               ├── ......
        └── ......
└── ......
```

**Comment by ywyue** [comment]
Close this issue for now. Feel free to reopen it if you have further concerns!
