### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by erasan23** [ywyue/RoomFormer#13]
Hi~ ywyue, thank you for your work.
When I execute the code "generate_point_cloud_stru3d.py", I get the following error. 
What should be added is that some files in the series of compressed packages named "Structured3D_panorama" that I downloaded were corrupted, so I had to delete part of the folder whose name format is "scene_xxxxx". I don't know if this will have any impact. At the time of the error, the code has processed all four of the zipped data.

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████Pointcloud size: 1036436█████████████████████████▋                                             | 152/198 [3:36:07<47:42, 62.23s/it]
 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                           | 153/198 [3:38:25<1:04:14, 85.65s/it]
 26%|███████████████████▍                                                      | 5/19 [28:54:28<80:56:31, 20813.65s/it]
Traceback (most recent call last):
  File "generate_point_cloud_stru3d.py", line 29, in <module>
    main(config())
  File "generate_point_cloud_stru3d.py", line 22, in main
    reader = PointCloudReaderPanorama(scene_path, random_level=0, generate_color=True, generate_normal=False)
  File "E:\YangMeiQi\git\RoomFormer\data_preprocess\stru3d\PointCloudReaderPanorama.py", line 25, in __init__
    self.point_cloud = self.generate_point_cloud(self.random_level, color=self.generate_color, normal=self.generate_normal)
  File "E:\YangMeiQi\git\RoomFormer\data_preprocess\stru3d\PointCloudReaderPanorama.py", line 75, in generate_point_cloud
    coords[:,:2] = np.round(coords[:,:2] / 10) * 10.
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by ywyue** [comment]
Hi @erasan23 , yes!  scene_xxxxx is required to correctly process the data. Please make sure to download and unzip the raw data correctly :)

**Comment by erasan23** [comment]
> I will try to remove the wrong data or re-download the datasets. Thanks!!
