### ISSUE TITLE
The indicators of training results are abnormal

### ISSUE THREAD

**Issue by erasan23** [ywyue/RoomFormer#14]
When I trained directly with the processed Structured3D dataset, the final training result seemed to be wrong. I don't know what I did wrong that led to this.

**When training, I used the command:**
python main.py --dataset_name=stru3d --dataset_root=dataru3d --num_queries=800 --num_polys=20 --semantic_classes=-1 --job_name=train_stru3d --num_workers=0

**The relevant indicators obtained after the training are as follows:**
Averaged stats: room_prec: 0.0000 (0.1604)  room_rec: 0.0000 (0.1415)  corner_prec: 0.0000 (0.0777)  corner_rec: 0.0000 (0.0607)  angles_prec: 0.0000 (0.0626)  angles_rec: 0.0000 (0.0500)  loss: 0.8760 (0.8640)  loss_ce: 0.1437 (0.1420)  loss_coords: 0.3569 (0.3627)  loss_raster: 0.3638 (0.3593)  loss_ce_unscaled: 0.0719 (0.0710)  loss_coords_unscaled: 0.0714 (0.0725)  loss_raster_unscaled: 0.3638 (0.3593)  cardinality_error_unscaled: 9.7000 (9.8400)

**The charts in wandb are as follows:**
![image](https://github.com/ywyue/RoomFormer/assets/121599924/23b0905a-062a-4672-bc08-9e2a388df78a)
![image](https://github.com/ywyue/RoomFormer/assets/121599924/d1dc6567-2e6b-4d1a-a337-6827eb523d50)

**My dataset file directory is shown below:**
![C_{TL6G( 68%}1V0P7 W_JV](https://github.com/ywyue/RoomFormer/assets/121599924/c806de1b-c76c-4b08-a0a7-c031941b52fc)

**Comment by ywyue** [comment]
Hi, could you please try setting --num_workers=2? btw, what's your pytorch version?

**Comment by erasan23** [comment]
When num_workers>0, this error occurs: EOFError:Ran out of input.
In addition, my pytorch version is 1.9.0+cu111.

**Comment by erasan23** [comment]
Thanks. The problem is solved by setting --num_worker=2. But for Windows, the code in **main.py** needs to be modified as follows:

First, add the following code:
![36$U0_3JJ12KGAGO(17PV%V](https://github.com/ywyue/RoomFormer/assets/121599924/877e9106-39f0-4bd6-85b3-20efa75ae36d)

Then, set the input parameter 'mutiprocessing_context' in the Data_loader:
![LR14_3112L~CFT@ ~JMDJP7](https://github.com/ywyue/RoomFormer/assets/121599924/d3ea1c45-3fe5-4d82-a1ac-387447d23680)

**Comment by ywyue** [comment]
It is great the problem was solved! Thanks.
