### ISSUE TITLE
Structured3D Data preprocessing problem

### ISSUE THREAD

**Issue by zhangzscn** [ywyue/RoomFormer#15]
Some data in Structured3D is lost, resulting in the failure of generating point cloud data. Have you used this tool to convert point clouds?

generate_point_cloud_stru3d.py

**Comment by zhangzscn** [comment]
some  error or missing data：

/Structured3D_panorama_11/Structured3D/scene_02212/2D_rendering/1058346/panorama/full/rgb_coldlight.png
/Structured3D_panorama_11/Structured3D/scene_02212/2D_rendering/175980/panorama/full/depth.png
/Structured3D_panorama_01/Structured3D/scene_00206/2D_rendering/141/panorama/full/rgb_coldlight.png

**Comment by ywyue** [comment]
Hi, yes, I used generate_point_cloud_stru3d.py to generate point clouds. If there is missing data, you may let the [Structured3D](https://github.com/bertjiazheng/Structured3D) team know.

**Comment by ywyue** [comment]
Closed this issue for now. Feel free to let me know if you have further concerns.

**Comment by zhangzscn** [comment]
Could you please share the lost data with me? Because you tried to use the tool to generate a point cloud, the data you downloaded should have the correct data.

missing data：
/Structured3D_panorama_11/Structured3D/scene_02213/2D_rendering/786544/panorama/full/depth.png
/Structured3D_panorama_11/Structured3D/scene_02213/2D_rendering/786544/panorama/full/depth.png
/Structured3D_panorama_11/Structured3D/scene_02212/2D_rendering/1058346/panorama/full/rgb_coldlight.png
/Structured3D_panorama_11/Structured3D/scene_02212/2D_rendering/175980/panorama/full/depth.png
/Structured3D_panorama_01/Structured3D/scene_00213/2D_rendering/22731/panorama/full/depth.png
/Structured3D_panorama_01/Structured3D/scene_00213/2D_rendering/22735/panorama/full/depth.png
/Structured3D_panorama_01/Structured3D/scene_00206/2D_rendering/141/panorama/full/rgb_coldlight.png
/Structured3D_panorama_13/Structured3D/scene_02608/2D_rendering/345/panorama/full/rgb_coldlight.png
/Structured3D_panorama_10/Structured3D/scene_02011/2D_rendering/2003/panorama/full/rgb_coldlight.png
/Structured3D_panorama_07/Structured3D/scene_01412/2D_rendering/143/panorama/full/depth.png
/Structured3D_panorama_09/Structured3D/scene_01815/2D_rendering/1429/panorama/full/depth.png
/Structured3D_panorama_09/Structured3D/scene_01815/2D_rendering/237/panorama/full/rgb_coldlight.png
/Structured3D_panorama_07/Structured3D/scene_01410/2D_rendering/176231/panorama/full/rgb_coldlight.png
/Structured3D_panorama_07/Structured3D/scene_01410/2D_rendering/180208/panorama/full/depth.png
/Structured3D_panorama_05/Structured3D/scene_01010/2D_rendering/1162/panorama/full/depth.png
/Structured3D_panorama_03/Structured3D/scene_00613/2D_rendering/794918/panorama/full/depth.png
/Structured3D_panorama_04/Structured3D/scene_00810/2D_rendering/1817/panorama/full/depth.png
/Structured3D_panorama_04/Structured3D/scene_00809/2D_rendering/3065/panorama/full/depth.png

**Comment by ywyue** [comment]
@zhangzscn   Hi, the [Structured3D Terms of Use](https://drive.google.com/open?id=13ZwWpU_557ZQccwOUJ8H5lvXD7MeZFMa) states that Researcher shall not redistribute the downloaded data, in whole or in part, through other media, but shall refer to the Database website (https://structured3d-dataset.org). I would share the data with you if the [Structured3D](https://github.com/bertjiazheng/Structured3D) team allows it.
