### ISSUE TITLE
Train on my  dataset

### ISSUE THREAD

**Issue by yyyyll0ss** [ywyue/RoomFormer#19]
Thank you for your open source work. When I tried to use my own three-channel image data set, it seemed that I could not train, there were no bugs in the training, and the loss was constantly decreasing, but the accuracy of the valuation set was always 0. Do you know the possible reasons for this?

**Comment by ywyue** [comment]
Thank you for your interest in our work. Based on the currently provided information, I can not judge the reasons - could you first try to plot the predictions and also ground truth to see whether they are reasonable? If the loss was decreasing but the accuracy was always 0, then it is very likely that there are some issues with the evaluation.

**Comment by ywyue** [comment]
Closed this issue for now. Feel free to let me know if you have further concerns.

**Comment by claumeh** [comment]
Can you share a sample density map from an independent dataset, so we can get a better idea on the prediction for different data? I would like to run the eval on this density map. Thanks

**Comment by ywyue** [comment]
hi @claumeh , what do you mean by "independent dataset"? If you already have your own 3D scan, it is easy to project the 3D point cloud to a density map. The projection code can also be found in this repo.

**Comment by claumeh** [comment]
hi @ywyue , here is a density map generated from my own dataset. But the results are not very accurate in all evaluation scenarios: 

- eval_stru3d
- eval_stru3d_sem_rich
- eval_stru3d_tight

Can you try to predict better results from this density map?
![03268](https://github.com/user-attachments/assets/c18175cd-06fc-4bac-85de-3bb8c1fa7c2a)

**Comment by claumeh** [comment]
Could you show the results you get from this density map. We just want to make sure that we infere it the right way and the density map has a correct structure

**Comment by ywyue** [comment]
Hi @claumeh , sorry I missed your message. I will reopen the issue now. 

The density map you show looks like the data for a whole floor. However, [Structured3D](https://structured3d-dataset.org/) (where the model was trained on) is a housing dataset. There is a clear domain gap between your data and Structured3D and I expect the performance of the model will degrade. In particular, the model never saw long corridors in Structured3D.

Could you please crop your point cloud or density map (e.g. the left bottom part) and see whether it can help the inference?
