### ISSUE TITLE
code

### ISSUE THREAD

**Issue by LUUUJ** [ywyue/RoomFormer#2]
This paper is great ! Can you publish the code? I will thank you very much!

**Comment by ywyue** [comment]
Thanks for your interest! We will publish the code as soon as the paper acceptance. Please stay tuned!

**Comment by zjhthu** [comment]
Hi, congratulations on the paper being accepted by CVPR 2023!  Will the code be released recently? Thanks a lot!

**Comment by ywyue** [comment]
Thanks! Yes, the code is expected to be released in mid-March.
