### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by K25801** [ywyue/RoomFormer#21]
Hi, thanks for your beautiful work. How can I visualize the results from the processed scenecad data?

**Comment by K25801** [comment]
In detail, when I'm testing scenecad datasets, the output I have is this:
![image](https://github.com/ywyue/RoomFormer/assets/123232856/d5dfb5f3-a277-46f3-835c-fa37b6a25db1)
![image](https://github.com/ywyue/RoomFormer/assets/123232856/f19b1c9f-1982-4e7a-b002-49d1b9eab125)

Seems not to be a well-reconstructed floor plan, is there any suggestions?

**Comment by ywyue** [comment]
Hi, thanks for your interest and kind words! I am sorry for the late reply.

> How can I visualize the results from the processed scenecad data?

You can visualize both the prediction and ground truth by setting `--plot_pred` , `--plot_density`,  and `--plot_gt` as `True` in `eval.py`.

> Seems not to be a well-reconstructed floor plan, is there any suggestions?

I am not sure why you think this is not a well-reconstructed floor plan. I have attached the raw 3D scan and ground truth annotation for this scene below:
![GT](https://github.com/ywyue/RoomFormer/assets/40747438/723641ca-adce-433c-b6c7-26e6a5e6da17)

As you can see, your attached output of the model is quite similar to the ground truth even though the 3D scan is quite noisy.
Let me know if you have any further concerns!
