### ISSUE TITLE
Results as Polygons and Vectors

### ISSUE THREAD

**Issue by claumeh** [ywyue/RoomFormer#23]
Hi ywyue,

thank you for your efforts and great work. 
I am able to get the results as .png files. Is there also a way of getting the results as polygons? Are the measurements of those polygons then in actual distances or is this downsampled to the density map 256×256 size?

Thanks,
Claudia

**Comment by ywyue** [comment]
Hi @claumeh , thanks for your interest in our work!

> I am able to get the results as .png files. Is there also a way of getting the results as polygons? 

Yes, polygons are already stored here: https://github.com/ywyue/RoomFormer/blob/33ad087f50f15fce04719828db8d2a56fd4b630f/engine.py#L351

> Are the measurements of those polygons then in actual distances or is this downsampled to the density map 256×256 size?

The coordinates of the vertices of those polygons are in density map space (256×256). Here is what we used to normalize the points: https://github.com/ywyue/RoomFormer/blob/33ad087f50f15fce04719828db8d2a56fd4b630f/data_preprocess/stru3d/stru3d_utils.py#L83C5-L83C26

To recover the coordinates the same with the 3D scans (in meters), it would be straightforward to write a function to de-normalize the predictions using the `normalization_dict`.

**Comment by ywyue** [comment]
Close for now. Feel free to reopen it if you have any further concerns.
