### ISSUE TITLE
    import native_rasterizer ImportError: xxx/code/RoomFormer/diff_ras/native_rasterizer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

### ISSUE THREAD

**Issue by lyx323** [ywyue/RoomFormer#25]
Dear authors,

Thank you very much for your work. I appreciate the idea of the paper.

Now, when i'm running the training or the eval code, There has been an error -- import native_rasterizer ImportError: xxx/code/RoomFormer/diff_ras/native_rasterizer.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v

my platform: ubuntu 20.04
GPU: TITAN XP
cuda： 11.1.0
python：3.8

How should I fix the problem, thanks a lot!

**Comment by ywyue** [comment]
Hi @lyx323 , thanks for your interest in our work! 

Have you set up the environment properly following the README? 

```shell
cd diff_ras
python setup.py build develop
``` 

Could you please show me the log after you run the above commands? Thank you.

**Comment by lyx323** [comment]
Hi，thanks for your reply.
I have set up the whole requirements of the ReadMe. And this is the log when i running 
'' cd diff_ras
python setup.py build develop '':

running build
running build_ext
/home/lyx/miniconda3/envs/lyx-py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
running develop
/home/lyx/miniconda3/envs/lyx-py38/lib/python3.8/site-packages/setuptools/command/develop.py:42: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  easy_install.initialize_options(self)
/home/lyx/miniconda3/envs/lyx-py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running egg_info
writing rasterizer.egg-info/PKG-INFO
writing dependency_links to rasterizer.egg-info/dependency_links.txt
writing top-level names to rasterizer.egg-info/top_level.txt
reading manifest file 'rasterizer.egg-info/SOURCES.txt'
writing manifest file 'rasterizer.egg-info/SOURCES.txt'
running build_ext
Creating /home/lyx/miniconda3/envs/lyx-py38/lib/python3.8/site-packages/rasterizer.egg-link (link to .)
rasterizer 0.0.0 is already the active version in easy-install.pth

Installed /home/lyx/code/RoomFormer/diff_ras
Processing dependencies for rasterizer==0.0.0
Finished processing dependencies for rasterizer==0.0.0
 Thank you so much!

**Comment by lyx323** [comment]
Hi
I deleted the folders 'build', 'native_rasterizer.cpython-38-x86_64-linux-gnu.so', '__pycache__', and 'rasterizer.egg-info' in the default path, and then ran `cd diff_ras followed by python setup.py build develop` to finally fix the error.

**Comment by ywyue** [comment]
Hi @lyx323 , if I understand correctly, you already fixed the error and I am closing the issue. Otherwise, feel free to reopen the issue again.
