### ISSUE TITLE
The native_rasterizer module cannot be found.

### ISSUE THREAD

**Issue by YAO-mm** [ywyue/RoomFormer#26]
Dear author,

I have recently been trying to run the Roomformer program you created. After setting up the environment and running the program, the system indicated that the native_rasterizer module could not be found. From the name, it doesn’t seem like a third-party module. Could you please let me know how I can find this module?

Thank you.

**Comment by ywyue** [comment]
Hey @YAO-mm , thanks for your interest! Could you please check this issue: https://github.com/ywyue/RoomFormer/issues/25
Let me know if the solution there cannot solve your problem.

**Comment by YAO-mm** [comment]
Thank you for your response
| |
yaomeng_1996
|
|
***@***.***
|
---- Replied Message ----
| From | Yuanwen ***@***.***> |
| Date | 8/28/2024 18:19 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [ywyue/RoomFormer] The native_rasterizer module cannot be found. (Issue #26) |

Hey @YAO-mm , thanks for your interest! Could you please check this issue: #25
