### ISSUE TITLE
Could you provide the data preprocessing codes? Thanks a lot!

### ISSUE THREAD

**Issue by MandyDongrs** [ywyue/RoomFormer#3]

**Comment by ywyue** [comment]
Hi, thanks for your interest! I will upload the data preprocessing scripts in the next few days.

**Comment by MandyDongrs** [comment]
Thank you~~

**Comment by ywyue** [comment]
Hi, sorry for the delay! I just uploaded the data preprocessing scripts and instructions [here](https://github.com/ywyue/RoomFormer/tree/main/data_preprocess). Please let me know if you have further issues!
