### ISSUE TITLE
detectron2.data

### ISSUE THREAD

**Issue by LUUUJ** [ywyue/RoomFormer#4]
ModuleNotFoundError:No module named 'detectron2.data'
Could you please provide the corresponding code?

**Comment by ywyue** [comment]
Hi, thanks for pointing out this! I just fixed that.

**Comment by LUUUJ** [comment]
Excuse me again.No such file or directory:'s3d_floorplan_eval/montefloor_data/test'Could you please give me the corresponding file？发自我的手机-------- 原始邮件 --------发件人： Yuanwen Yue ***@***.***>日期： 2023年3月21日周二 傍晚5:38收件人： ywyue/RoomFormer ***@***.***>抄送： Ziqiong LU ***@***.***>, Author ***@***.***>主    题： Re: [ywyue/RoomFormer] detectron2.data (Issue #4)
Hi, thanks for pointing this out! I just fixed that.

**Comment by ywyue** [comment]
Hi, have you extracted "montefloor_data" into "s3d_floorplan_eval"? (please see: https://github.com/ywyue/RoomFormer#structured3d-1)

**Comment by LUUUJ** [comment]
Sorry, I deleted the question by mistake. I have solved it, thank you for your reply!
