### ISSUE TITLE
How to get the  semantic-rich floorplan result?

### ISSUE THREAD

**Issue by SRCB-JHJ** [ywyue/RoomFormer#5]
How to get the  semantic-rich floorplan result?

**Comment by ywyue** [comment]
Hi, the instructions for the semantic-rich floorplan will come soon, hopefully within the next week.

**Comment by ywyue** [comment]
Hi, the instructions and code for the semantic-rich floorplan have been added. Close the issue for now. Feel free to reopen it if you have further questions!
