### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by zuixiaosanlang** [ywyue/RoomFormer#6]
i run this script:
eval_stru3d_tight.sh

get:
![image](https://user-images.githubusercontent.com/20105627/228721527-6de567eb-5d62-4f1a-b0d6-3b2addb1ecbf.png)

and in the folder checkpoints/eval_stru3d_tight:
gt:
![image](https://user-images.githubusercontent.com/20105627/228722025-924c7041-47de-4bd0-9721-d84e0bcfe560.png)

pred:
![image](https://user-images.githubusercontent.com/20105627/228722026-d30ccc9c-588a-4f1f-a48c-0b770c95811e.png)

map:
![image](https://user-images.githubusercontent.com/20105627/228722062-bd34ebbf-fe69-4273-825c-9050e37890f6.png)

my CUDA 11.6
![image](https://user-images.githubusercontent.com/20105627/228722633-fbd6e7fc-60b5-4747-a714-edd12cb7fb9a.png)

what is wrong ??
thanks

**Comment by zuixiaosanlang** [comment]
ohh,
cuda and torch not match.

**Comment by SRCB-JHJ** [comment]
My CUDA version is 11.1, and I totally follow your instruction to prepare the environment. But I got similar problem like this 
![123](https://user-images.githubusercontent.com/61730437/228754410-cda2518a-6ecf-4f6b-9d9f-8b02a894c109.JPG)
