### ISSUE TITLE
run eval_stru3d_sem_rich.sh failed

### ISSUE THREAD

**Issue by zuixiaosanlang** [ywyue/RoomFormer#7]
it is normal to run 
eval_stru3d.sh, eval_stru3d_tight.sh, eval_scenecas.sh.

and get fine results.

But when i run  eval_stru3d_sem_rich.sh, 
it failed.
![image](https://user-images.githubusercontent.com/20105627/228772294-ddda6da7-d2e3-4d0c-bd12-21e3872d2075.png)

also my env is different.
torch 1.13.1
cuda 11.6

i donot know if i must change my env

**Comment by ywyue** [comment]
Hi, could you please try setting --plot_pred=False and --plot_gt=False and see whether you can obtain reasonable metrics?

**Comment by zuixiaosanlang** [comment]
@ywyue 
do as you say, 
it is ok now,
thanks
![image](https://user-images.githubusercontent.com/20105627/228788361-cb722a6a-4345-49f9-aea3-69adabc646aa.png)

**Comment by zuixiaosanlang** [comment]
@ywyue 
hi, 
do you know how to fix it, 
if  --plot_pred=True and --plot_gt=True

**Comment by ywyue** [comment]
@zuixiaosanlang  Hi, I tried to reproduce this error but didn't encounter this. Could you check the value of `gt_sem_rich` in this [line](https://github.com/ywyue/RoomFormer/blob/e9757ff7aef1410636f7226625a8a8b305138e09/engine.py#L248)?

**Comment by zuixiaosanlang** [comment]
@ywyue 
thanks. 
i change shapely 2.0.1 to 1.8.2
it is ok now.
