### ISSUE TITLE
MSDeformAttnFunction.apply,  can be implemented by pytorch?

### ISSUE THREAD

**Issue by zuixiaosanlang** [ywyue/RoomFormer#9]
i want to save the model by jit.trace: 
model = torch.jit.trace()
model.save(xxx.pt)

but failed
![image](https://user-images.githubusercontent.com/20105627/231107746-8bb653b0-c8b8-4652-8faf-b6822894b315.png)

thanks.

**Comment by ywyue** [comment]
Hi, we just use the MSDeformAttn from [Deformable-DETR](https://github.com/fundamentalvision/Deformable-DETR). They implement the MSDeformAttn using C.
